services:
  api-animals:
    build:
      context: .
      dockerfile: packages/animals/Dockerfile
      args:
        - "PORT=${ANIMALS_API_PORT}"
    environment:
      - "NODE_ENV=${ANIMALS_API_NODE_ENV}"
      - "PORT=${ANIMALS_API_PORT}"
      - "DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"    
    expose:
      - "${ANIMALS_API_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${ANIMALS_API_PORT}/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./packages/animals:/app/packages/animals
      - ./packages/core:/app/packages/core
      - ./packages/data:/app/packages/data
      - ./packages/domain:/app/packages/domain

  api-batches:
    build:
      context: ./
      dockerfile: packages/batches/Dockerfile
      args:
        - "PORT=${BATCHES_API_PORT}"
    environment:
      - "NODE_ENV=${BATCHES_API_NODE_ENV}"
      - "PORT=${BATCHES_API_PORT}"
      - "DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    expose:
      - "${BATCHES_API_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${BATCHES_API_PORT}/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./packages/batches:/app/packages/batches
      - ./packages/core:/app/packages/core
      - ./packages/data:/app/packages/data
      - ./packages/domain:/app/packages/domain

  bff:
    build:
      context: ./
      dockerfile: packages/bff/Dockerfile
      args:
        - "PORT=${BFF_PORT}"
    environment:
      - "NODE_ENV=${BFF_NODE_ENV}"
      - "PORT=${BFF_PORT}"
      - "BATCH_API_URL=http://api-batches:${BATCHES_API_PORT}"
      - "ANIMAL_API_URL=http://api-animals:${ANIMALS_API_PORT}"
      - CACHE_TTL=60
      - CACHE_MAX_ITEMS=1000
      - CACHE_REDIS_URL=redis://redis:6379
    ports:
      - "${BFF_PORT}:${BFF_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${BFF_PORT}/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      api-animals:
        condition: service_healthy
      api-batches:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./packages/bff:/app/packages/bff
      - ./packages/core:/app/packages/core
      - ./packages/data:/app/packages/data
      - ./packages/domain:/app/packages/domain

  postgres:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-rc2-alpine
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
