#!/usr/bin/env sh

echo "FORMATTING CODE" && npm run format && git add -u
echo ""

echo "LINTING CODE" && npm run lint && git add -u
echo ""

echo "LITING COMMIT" && npm run commit:lint "${1}"
echo ""
